### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by stevelacy** [stevelacy/modalify#1]
Add options:
- [ ] Close all open modals when new modal is opened
- [X] Add close event to close modal from another element.

Plugin:
- [ ] Click anywhere outside of modal to close
